#############################################################################
# Makefile for building: peerster
# Generated by qmake (2.01a) (Qt 4.8.5) on: Sun Dec 14 15:27:20 2014
# Project:  peerster.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile peerster.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -I. -I/usr/include/QtCrypto -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib64 -L/usr/lib64 -lqca -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cc \
		NetSocket.cc \
		Peer.cc \
		SageTextEdit.cc \
		PrivateMessageWindow.cc \
		FileMetadata.cc \
		TrackedFileMetadata.cc \
		DownloadWindow.cc \
		ChordDHT.cc moc_main.cpp \
		moc_NetSocket.cpp \
		moc_SageTextEdit.cpp \
		moc_PrivateMessageWindow.cpp \
		moc_DownloadWindow.cpp
OBJECTS       = main.o \
		NetSocket.o \
		Peer.o \
		SageTextEdit.o \
		PrivateMessageWindow.o \
		FileMetadata.o \
		TrackedFileMetadata.o \
		DownloadWindow.o \
		ChordDHT.o \
		moc_main.o \
		moc_NetSocket.o \
		moc_SageTextEdit.o \
		moc_PrivateMessageWindow.o \
		moc_DownloadWindow.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/crypto.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		peerster.pro
QMAKE_TARGET  = BitTorrEnnant
DESTDIR       = 
TARGET        = BitTorrEnnant

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: peerster.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/crypto.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libqca.prl \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl \
		/usr/lib64/libQtNetwork.prl
	$(QMAKE) -o Makefile peerster.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/crypto.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libqca.prl:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
/usr/lib64/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile peerster.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/peerster1.0.0 || $(MKDIR) .tmp/peerster1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/peerster1.0.0/ && $(COPY_FILE) --parents main.hh NetSocket.hh Peer.hh SageTextEdit.hh PrivateMessageWindow.hh FileMetadata.hh TrackedFileMetadata.hh DownloadWindow.hh ChordDHT.hh .tmp/peerster1.0.0/ && $(COPY_FILE) --parents main.cc NetSocket.cc Peer.cc SageTextEdit.cc PrivateMessageWindow.cc FileMetadata.cc TrackedFileMetadata.cc DownloadWindow.cc ChordDHT.cc .tmp/peerster1.0.0/ && (cd `dirname .tmp/peerster1.0.0` && $(TAR) peerster1.0.0.tar peerster1.0.0 && $(COMPRESS) peerster1.0.0.tar) && $(MOVE) `dirname .tmp/peerster1.0.0`/peerster1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/peerster1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_main.cpp moc_NetSocket.cpp moc_SageTextEdit.cpp moc_PrivateMessageWindow.cpp moc_DownloadWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main.cpp moc_NetSocket.cpp moc_SageTextEdit.cpp moc_PrivateMessageWindow.cpp moc_DownloadWindow.cpp
moc_main.cpp: NetSocket.hh \
		Peer.hh \
		SageTextEdit.hh \
		FileMetadata.hh \
		TrackedFileMetadata.hh \
		ChordDHT.hh \
		main.hh
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) main.hh -o moc_main.cpp

moc_NetSocket.cpp: NetSocket.hh
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) NetSocket.hh -o moc_NetSocket.cpp

moc_SageTextEdit.cpp: SageTextEdit.hh
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) SageTextEdit.hh -o moc_SageTextEdit.cpp

moc_PrivateMessageWindow.cpp: SageTextEdit.hh \
		PrivateMessageWindow.hh
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) PrivateMessageWindow.hh -o moc_PrivateMessageWindow.cpp

moc_DownloadWindow.cpp: DownloadWindow.hh
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) DownloadWindow.hh -o moc_DownloadWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cc main.hh \
		NetSocket.hh \
		Peer.hh \
		SageTextEdit.hh \
		FileMetadata.hh \
		TrackedFileMetadata.hh \
		ChordDHT.hh \
		PrivateMessageWindow.hh \
		DownloadWindow.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

NetSocket.o: NetSocket.cc NetSocket.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NetSocket.o NetSocket.cc

Peer.o: Peer.cc Peer.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Peer.o Peer.cc

SageTextEdit.o: SageTextEdit.cc SageTextEdit.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SageTextEdit.o SageTextEdit.cc

PrivateMessageWindow.o: PrivateMessageWindow.cc PrivateMessageWindow.hh \
		SageTextEdit.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PrivateMessageWindow.o PrivateMessageWindow.cc

FileMetadata.o: FileMetadata.cc FileMetadata.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileMetadata.o FileMetadata.cc

TrackedFileMetadata.o: TrackedFileMetadata.cc TrackedFileMetadata.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TrackedFileMetadata.o TrackedFileMetadata.cc

DownloadWindow.o: DownloadWindow.cc DownloadWindow.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DownloadWindow.o DownloadWindow.cc

ChordDHT.o: ChordDHT.cc ChordDHT.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChordDHT.o ChordDHT.cc

moc_main.o: moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp

moc_NetSocket.o: moc_NetSocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NetSocket.o moc_NetSocket.cpp

moc_SageTextEdit.o: moc_SageTextEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SageTextEdit.o moc_SageTextEdit.cpp

moc_PrivateMessageWindow.o: moc_PrivateMessageWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PrivateMessageWindow.o moc_PrivateMessageWindow.cpp

moc_DownloadWindow.o: moc_DownloadWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DownloadWindow.o moc_DownloadWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

